### ISSUE TITLE
Error when creating pypsa network (table names?)

### ISSUE THREAD

**Issue by simnh** [openego/eTraGo#1]
I tried to run the snapshot clustering, but there is still the following error: 

```
Traceback (most recent call last):
  File "snaphot_clustering_app.py", line 159, in <module>
    network, snapshots = create_powerflow_problem(timerange, components)
  File "/home/simon/uni/repos/snapshot_clustering/eTraGo/venv/src/ego.powerflow/egopowerflow/tools/io.py", line 172, in create_powerflow_problem
    component)
  File "/home/simon/uni/repos/snapshot_clustering/eTraGo/venv/src/pypsa/pypsa/io.py", line 187, in import_components_from_dataframe
    attrs = network.components[cls_name]["attrs"]
KeyError: 'Storage'

```

I guess there is still something wrong with the table names and derived component names (should 
resolve to StorageUnit and not Storage I guess)

**Comment by s3pp** [comment]
This should do the trick openego/ego.powerflow@5dadbf5aed67d3fe280457d505833c3ebbcbc203.

**Comment by s3pp** [comment]
I updated once again your requirements.

**Comment by s3pp** [comment]
I guess, I should leave the ticket open. : ) Everything is so shaky atm, sry for that!

**Comment by s3pp** [comment]
[io.py](https://github.com/openego/ego.powerflow/blob/dev/egopowerflow/tools/io.py) in ego.powerflow was rewritten and is up and running for a while. Subsequently this issue is closed.
