### ISSUE TITLE
Load k-means cluster

### ISSUE THREAD

**Issue by BartelsJ** [openego/eTraGo#140]
A new [branch ](https://github.com/openego/eTraGo/tree/features/load_k_cluster) was created to enable the loading of former created cluster networks. At the moment there are problems in the later aggregation of lines while combining data tables with pandas.join(). 

Traceback (most recent call last):

  File "<ipython-input-11-a894517d1f07>", line 1, in <module>
    runfile('/home/jbartels/projekte/open-ego/eTraGo/etrago/appl.py', wdir='/home/jbartels/projekte/open-ego/eTraGo')

  File "/home/jbartels/miniconda3/envs/julian/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "/home/jbartels/miniconda3/envs/julian/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/jbartels/projekte/open-ego/eTraGo/etrago/appl.py", line 340, in <module>
    network = etrago(args)

  File "/home/jbartels/projekte/open-ego/eTraGo/etrago/appl.py", line 278, in etrago
    network = kmean_clustering(network, n_clusters=args['k_mean_clustering'], load_cluster=args['load_cluster'])

  File "/home/jbartels/projekte/open-ego/eTraGo/etrago/cluster/networkclustering.py", line 438, in kmean_clustering
    clustering = get_clustering_from_busmap(network, busmap, aggregate_generators_weighted=True, aggregate_one_ports=aggregate_one_ports)

  File "/home/jbartels/projekte/open-ego/eTraGo/src/pypsa/pypsa/networkclustering.py", line 250, in get_clustering_from_busmap
    buses, linemap, linemap_p, linemap_n, lines = get_buses_linemap_and_lines(network, busmap, line_length_factor, bus_strategies)

  File "/home/jbartels/projekte/open-ego/eTraGo/src/pypsa/pypsa/networkclustering.py", line 234, in get_buses_linemap_and_lines
    lines, linemap_p, linemap_n, linemap = aggregatelines(network, buses, interlines, line_length_factor)

  File "/home/jbartels/projekte/open-ego/eTraGo/src/pypsa/pypsa/networkclustering.py", line 219, in aggregatelines
    linemap_p = interlines_p.join(lines['name'], on=['bus0_s', 'bus1_s'])['name']

  File "/home/jbartels/miniconda3/envs/julian/lib/python3.6/site-packages/pandas/core/frame.py", line 4669, in join
    rsuffix=rsuffix, sort=sort)

  File "/home/jbartels/miniconda3/envs/julian/lib/python3.6/site-packages/pandas/core/frame.py", line 4684, in _join_compat
    suffixes=(lsuffix, rsuffix), sort=sort)

  File "/home/jbartels/miniconda3/envs/julian/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 53, in merge
    copy=copy, indicator=indicator)

  File "/home/jbartels/miniconda3/envs/julian/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 553, in __init__
    self._validate_specification()

  File "/home/jbartels/miniconda3/envs/julian/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 942, in _validate_specification
    raise ValueError('len(left_on) must equal the number '

ValueError: len(left_on) must equal the number of levels in the index of "right"

**Comment by ulfmueller** [comment]
I think this was solved since the feature got merged into dev, correct @BartelsJ ?
Maybe as a pre-docu give some explanation of the new functionality in a few words here and then we close this issue, ok?

**Comment by BartelsJ** [comment]
Sure. A new argument "load_cluster" was introduced into the appl.py to load former calculated k-means grids.

The application of k-means saves a file 'cluster_coord_k_ii_result' (ii is the number of chosen k) containing the coordinates of all new k-nodes automatically. To load these into a new simulation, set 'load_cluster = /Path/to/file/cluster_coord_k_ii_result" in the arguments of appl.py. Done in #162.
