### ISSUE TITLE
KeyError 'Link' in dev

### ISSUE THREAD

**Issue by MarlonSchlemminger** [openego/eTraGo#156]
I get an error while building the network with the current dev-branch. Gridversion is 0.3.0pre1. Will this be fixed after the dp run? 

Warning: Relation Link does not exist.
Traceback (most recent call last):

  File "<ipython-input-1-b0a26e043351>", line 1, in <module>
    runfile('C:/Users/marlo/Anaconda3/envs/openego/Lib/site-packages/eTraGo/etrago/appl.py', wdir='C:/Users/marlo/Anaconda3/envs/openego/Lib/site-packages/eTraGo/etrago')

  File "C:\Users\marlo\Anaconda3\envs\openego\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\Users\marlo\Anaconda3\envs\openego\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/marlo/Anaconda3/envs/openego/Lib/site-packages/eTraGo/etrago/appl.py", line 409, in <module>
    network = etrago(args)

  File "C:/Users/marlo/Anaconda3/envs/openego/Lib/site-packages/eTraGo/etrago/appl.py", line 265, in etrago
    network = scenario.build_network()

  File "C:\Users\marlo\Anaconda3\envs\openego\lib\site-packages\etrago\etrago\tools\io.py", line 287, in build_network
    df = self.fetch_by_relname(comp)

  File "C:\Users\marlo\Anaconda3\envs\openego\lib\site-packages\etrago\etrago\tools\io.py", line 155, in fetch_by_relname
    ormclass = self._mapped[name]

KeyError: 'Link'

**Comment by ulfmueller** [comment]
Please check out ego.io in the dev branch then it'll work. yes after a new dp and ego.io release this will be 'fixed'.
