### ISSUE TITLE
plot.py throws error when there are extendable links and p_nom_opt is 0 for some links (preliminary fixed)

### ISSUE THREAD

**Issue by wheitkoetter** [openego/eTraGo#308]
ERROR MESSAGE

Runtime etrago [min]: 2.45
2020-10-12 16:12:39.514367
Traceback (most recent call last):
  File "appl_WH.py", line 393, in <module>
    etrago.plot_grid(line_colors='line_loading') # to show other plots, adjust the line_colors argument according to https://github.com/openego/eTraGo/blob/a0d109cbd94be6c6f8aad4704e5ced15b5e46874/etrago/tools/plot.py#L1314 
  File "/home/wilkohe/etrago_segm_ptg/eTraGo/etrago/tools/plot.py", line 1413, in plot_grid
    (calc_dc_loading(network, timesteps)/rep_snapshots).values
  File "/home/wilkohe/miniconda3/envs/etrago_segm_ptg/lib/python3.6/site-packages/pandas/core/indexing.py", line 670, in __setitem__
    iloc._setitem_with_indexer(indexer, value)
  File "/home/wilkohe/miniconda3/envs/etrago_segm_ptg/lib/python3.6/site-packages/pandas/core/indexing.py", line 1802, in _setitem_with_indexer
    self.obj._mgr = self.obj._mgr.setitem(indexer=indexer, value=value)
  File "/home/wilkohe/miniconda3/envs/etrago_segm_ptg/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 534, in setitem
    return self.apply("setitem", indexer=indexer, value=value)
  File "/home/wilkohe/miniconda3/envs/etrago_segm_ptg/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 406, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/wilkohe/miniconda3/envs/etrago_segm_ptg/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 855, in setitem
    check_setitem_lengths(indexer, value, values)
  File "/home/wilkohe/miniconda3/envs/etrago_segm_ptg/lib/python3.6/site-packages/pandas/core/indexers.py", line 152, in check_setitem_lengths
    "cannot set using a list-like indexer "
ValueError: cannot set using a list-like indexer with a different length than the value
 ******************
REASON: 
The following command in the function plot_grid() refers to all links in the network:
flow.iloc[flow.index.get_level_values('component') == 'Link'] = 

it shall be set equal to 
= (calc_dc_loading(network, timesteps)/rep_snapshots).values

But the latter does not contain links with p_nom_opt_max = 0, due to 

return (mul_weighting(network, link_load).loc[network.snapshots[timesteps]]
            .abs().sum()[network.links.index]/p_nom_opt_max).dropna()

in the last line of calc_dc_loading() function.
**************
POSSIBLE FIX:
Replace .dropna() with .fillna()
(see also commit which I will link here. But I am not sure, whether that causes any other problems, to replace it like this)

**Comment by ClaraBuettner** [comment]
This bug was fixed when the plotting module was updated.
