### ISSUE TITLE
Lifetime values of buses do not agree

### ISSUE THREAD

**Issue by fwitte** [openego/eTraGo#394]
I keep getting the following error in k_means clustering of the electricity grid when running `appl.py` in the current dev version on the CI dump from 28.02., also see https://github.com/openego/eTraGo/pull/367#issuecomment-1060278086.

```
Traceback (most recent call last):
  File "etrago/appl.py", line 441, in <module>
    etrago = run_etrago(args, json_path=None)
  File "etrago/appl.py", line 403, in run_etrago
    etrago.kmean_clustering()
  File "/home/witt_fa/eGon/eTraGo/etrago/cluster/networkclustering.py", line 1051, in run_kmeans_clustering
    self.clustering = kmean_clustering(self)
  File "/home/witt_fa/eGon/eTraGo/etrago/cluster/networkclustering.py", line 983, in kmean_clustering
    clustering = get_clustering_from_busmap(
  File "/home/witt_fa/anaconda3/envs/etrago_env/lib/python3.8/site-packages/pypsa/networkclustering.py", line 255, in get_clustering_from_busmap
    buses, linemap, linemap_p, linemap_n, lines, lines_t = get_buses_linemap_and_lines(network, busmap, line_length_factor, bus_strategies, with_time)
  File "/home/witt_fa/anaconda3/envs/etrago_env/lib/python3.8/site-packages/pypsa/networkclustering.py", line 235, in get_buses_linemap_and_lines
    lines, linemap_p, linemap_n, linemap, lines_t = aggregatelines(network, buses, interlines, line_length_factor, with_time)
  File "/home/witt_fa/anaconda3/envs/etrago_env/lib/python3.8/site-packages/pypsa/networkclustering.py", line 203, in aggregatelines
    lines = interlines_c.groupby(['bus0_s', 'bus1_s']).apply(aggregatelinegroup)
  File "/home/witt_fa/anaconda3/envs/etrago_env/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1275, in apply
    result = self._python_apply_general(f, self._selected_obj)
  File "/home/witt_fa/anaconda3/envs/etrago_env/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1309, in _python_apply_general
    keys, values, mutated = self.grouper.apply(f, data, self.axis)
  File "/home/witt_fa/anaconda3/envs/etrago_env/lib/python3.8/site-packages/pandas/core/groupby/ops.py", line 852, in apply
    res = f(group)
  File "/home/witt_fa/anaconda3/envs/etrago_env/lib/python3.8/site-packages/pypsa/networkclustering.py", line 200, in aggregatelinegroup
    data.update((f, consense[f](l[f])) for f in columns.difference(data))
  File "/home/witt_fa/anaconda3/envs/etrago_env/lib/python3.8/site-packages/pypsa/networkclustering.py", line 200, in <genexpr>
    data.update((f, consense[f](l[f])) for f in columns.difference(data))
  File "/home/witt_fa/anaconda3/envs/etrago_env/lib/python3.8/site-packages/pypsa/networkclustering.py", line 49, in consense
    assert ((x == v).all() or x.isnull().all()), (
AssertionError: In Bus cluster lifetime the values of attribute lifetime do not agree:
Line
27567     inf
27602    40.0
Name: lifetime, dtype: float64
```

Any ideas, what to do here?

**Comment by fwitte** [comment]
Thank you!

**Comment by ClaraBuettner** [comment]
This is already fixed in eTraGo:
https://github.com/openego/eTraGo/blob/23e1da32422b637e304e80de14194dc406aef277/etrago/tools/utilities.py#L2772-L2775
