### ISSUE TITLE
Compatibility between dev branch and dump backups

### ISSUE THREAD

**Issue by pieterhexen** [openego/eTraGo#440]
In this issue we would like to list all compatibilities resp. incompatabilites regarding the dev branch and the dump backup datasets.
Update whenever a new dump is released.

**Comment by ClaraBuettner** [comment]
> [ba675e0](https://github.com/openego/eTraGo/commit/ba675e0cf9c1d38075e5b2ca77a57980490099d8) with dumps egon-data-dev-grid_0907 and test-egon-data-dev-grid_0206 works as intended, when
> 
> https://github.com/openego/eTraGo/blob/ba675e0cf9c1d38075e5b2ca77a57980490099d8/etrago/tools/plot.py#L35-L37
> is commented (#426)
> and
> 
> https://github.com/openego/eTraGo/blob/ba675e0cf9c1d38075e5b2ca77a57980490099d8/etrago/appl.py#L54
> is set to False.

Interesting, did you also try to run the current dev branch? I was able to run the default settings on dev with the data of `egon-data-dev-grid_0906.backup` (I renamed the file in order to refer to the correct month). 

I installed cartopy manually (see [#434](https://github.com/openego/eTraGo/pull/434#issuecomment-1137035812)). 
When the optimization is only running without pyomo, I would assume that it is not caused by the data model. Could you maybe post the Error log?

**Comment by pieterhexen** [comment]
> When the optimization is only running without pyomo, I would assume that it is not caused by the data model. Could you maybe post the Error log?

This is the traceback for the error coming from https://github.com/openego/eTraGo/blob/ba675e0cf9c1d38075e5b2ca77a57980490099d8/etrago/appl.py#L54

INFO:pypsa.opf:Building pyomo model using `kirchhoff` formulation
Traceback (most recent call last):
  File "etrago/appl.py", line 486, in <module>
    etrago = run_etrago(args, json_path=None)
  File "etrago/appl.py", line 466, in run_etrago
    etrago.lopf()
  File "/home/eTrago/etrago/tools/execute.py", line 251, in lopf
    method=self.args['method'])
  File "/home/eTrago/etrago/tools/execute.py", line 178, in iterate_lopf
    run_lopf(etrago, extra_functionality, method)
  File "/home/eTrago/etrago/tools/execute.py", line 121, in run_lopf
    formulation=etrago.args['model_formulation'])
  File "/home/mambaforge/envs/etrago/lib/python3.7/site-packages/pypsa/components.py", line 658, in lopf
    return network_lopf(self, **args)
  File "/home/mambaforge/envs/etrago/lib/python3.7/site-packages/pypsa/opf.py", line 1664, in network_lopf
    formulation=formulation, ptdf_tolerance=ptdf_tolerance)
  File "/home/mambaforge/envs/etrago/lib/python3.7/site-packages/pypsa/opf.py", line 1459, in network_lopf_build_model
    define_generator_variables_constraints(network,snapshots)
  File "/home/mambaforge/envs/etrago/lib/python3.7/site-packages/pypsa/opf.py", line 111, in define_generator_variables_constraints
    list(extendable_gens_i), snapshots)
  File "/home/mambaforge/envs/etrago/lib/python3.7/site-packages/pypsa/opt.py", line 183, in l_constraint
    for i in v._index:
AttributeError: 'IndexedConstraint' object has no attribute '_index'

**Comment by pieterhexen** [comment]
>Edit: I had a look at some issues in pypsa. There was an issue with pyomo version 6.4.1, you have to use an older version (e.g. 6.4)
Thanks! When using pyomo 6.4.0 the optimization works fine.

**Comment by AmeliaNadal** [comment]
> > Edit: I had a look at some issues in pypsa. There was an issue with pyomo version 6.4.1, you have to use an older version (e.g. 6.4)
> 
> Thanks! When using pyomo 6.4.0 the optimization works fine.

Should we maybe limit the pyomo version in the [setup.py](https://github.com/openego/eTraGo/blob/dev/setup.py)?

**Comment by pieterhexen** [comment]
For the current dev branch and ci_dump (2022-08-23_egon-data-CI-grid.backup) there a several problems accrueing:
```
WARNING:pypsa.io:Components Index(['10787', '14151', '14996', '15174', '16086', '16114', '16163', '16186',
       '16196', '16443', '16444', '16529', '16534', '16661', '16672', '16925',
       '17180', '19722', '21851', '22007', '22346', '23620', '23668', '23701',
       '24056', '24185', '25404', '25419', '28120', '28150', '28169', '28213',
       '28533', '28720', '29067', '29079', '29082', '3956', '4731', '5693',
       '5839', '7047', '7070', '7381', '7413', '7751', '7752', '7983', '8010',
       '8015', '8353', '9296'],
      dtype='object', name='Line') for attribute s_max_pu of Line are not in main components dataframe lines
INFO:etrago.tools.io:Importing Transformers from database
C:\ProgramData\mambaforge\envs\test\lib\site-packages\pyproj\crs\crs.py:131: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
WARNING:pypsa.io:The following Transformer have buses which are not defined:
Index(['27601'], dtype='object', name='trafo_id')
INFO:etrago.tools.io:Importing Links from database
C:\ProgramData\mambaforge\envs\test\lib\site-packages\pyproj\crs\crs.py:131: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
WARNING:pypsa.io:The following Link have buses which are not defined:
Index(['7589', '7590', '7591', '7593', '7594', '7595', '7596', '7597', '7600',
       '7601',
       ...
       '54960', '54964', '54965', '54967', '54970', '54980', '54997', '55012',
       '55121', '55856'],
      dtype='object', name='link_id', length=2945)
WARNING:pypsa.io:The following Link have buses which are not defined:
Index(['28968', '28969', '7589', '7591', '7592', '7594', '7598', '7599',
       '7600', '7601',
       ...
       '58230', '58231', '58232', '58233', '58235', '58236', '58237', '58239',
       '58240', '54627'],
      dtype='object', name='link_id', length=2283)
INFO:etrago.tools.io:Importing Loads from database
WARNING:pypsa.io:The following Load have buses which are not defined:
Index(['7908', '7912', '7913', '7914', '7916', '7917', '15603', '15619',
       '15651', '15669',
       ...
       '30746', '30748', '30750', '30752', '30754', '30758', '30760', '30762',
       '30766', '30768'],
      dtype='object', name='load_id', length=2216)
INFO:etrago.tools.io:Importing Generators from database
WARNING:pypsa.io:The following Generator have buses which are not defined:
Index(['161', '162', '163', '165', '167', '169', '170', '172', '173', '177',
       ...
       '21567', '21570', '21574', '21578', '21584', '21593', '21555', '21563',
       '21571', '21589'],
      dtype='object', name='generator_id', length=104)
INFO:etrago.tools.io:Importing Storages from database
WARNING:pypsa.io:The following StorageUnit have buses which are not defined:
Index(['48', '50', '53', '54', '55', '56', '57', '62', '64', '66', '68', '69',
       '70', '348', '404', '572', '783', '1424', '1678', '1776', '1995',
       '2530', '2590', '2856', '3062', '3114', '3294', '3344', '4100', '4135',
       '4207', '4295'],
      dtype='object', name='storage_id')
INFO:etrago.tools.io:Importing Stores from database
WARNING:pypsa.io:The following Store have buses which are not defined:
Index(['7728', '7729', '7715', '7716', '7717', '7718', '7719', '7720', '7721',
       '7722',
       ...
       '23818', '23819', '23820', '23821', '23822', '23824', '23825', '23826',
       '23828', '23829'],
      dtype='object', name='store_id', length=2385)
INFO:etrago.tools.network:Imported network from db
INFO:pypsa.io:Exported network ci_dump_ehv_clustered has links, loads, generators, transformers, buses, storage_units, stores, lines
INFO:etrago.cluster.networkclustering:Start k-mean clustering
WARNING:pypsa.io:The following Line have buses which are not defined:
Index(['T27601'], dtype='object', name='name')
WARNING:pypsa.io:The following Generator have buses which are not defined:
Index(['161', '162', '163', '165', '167', '169', '170', '172', '173', '177',
       ...
       '21567', '21570', '21574', '21578', '21584', '21593', '21555', '21563',
       '21571', '21589'],
      dtype='object', name='name', length=104)
WARNING:pypsa.io:The following Line have buses which are not defined:
Index(['T27601'], dtype='object', name='Line')
WARNING:pypsa.io:The following Link have buses which are not defined:
Index(['7589', '7590', '7591', '7593', '7594', '7595', '7596', '7597', '7600',
       '7601',
       ...
       '54960', '54964', '54965', '54967', '54970', '54980', '54997', '55012',
       '55121', '55856'],
      dtype='object', name='name', length=2945)
WARNING:pypsa.io:The following Link have buses which are not defined:
Index(['28968', '28969', '7589', '7591', '7592', '7594', '7598', '7599',
       '7600', '7601',
       ...
       '58230', '58231', '58232', '58233', '58235', '58236', '58237', '58239',
       '58240', '54627'],
      dtype='object', name='name', length=2283)
WARNING:pypsa.io:The following Load have buses which are not defined:
Index(['7908', '7912', '7913', '7914', '7916', '7917', '15603', '15619',
       '15651', '15669',
       ...
       '30746', '30748', '30750', '30752', '30754', '30758', '30760', '30762',
       '30766', '30768'],
      dtype='object', name='name', length=2216)
WARNING:pypsa.io:The following StorageUnit have buses which are not defined:
Index(['48', '50', '53', '54', '55', '56', '57', '62', '64', '66', '68', '69',
       '70', '348', '404', '572', '783', '1424', '1678', '1776', '1995',
       '2530', '2590', '2856', '3062', '3114', '3294', '3344', '4100', '4135',
       '4207', '4295'],
      dtype='object', name='name')
WARNING:pypsa.io:The following Store have buses which are not defined:
Index(['7728', '7729', '7715', '7716', '7717', '7718', '7719', '7720', '7721',
       '7722',
       ...
       '23818', '23819', '23820', '23821', '23822', '23824', '23825', '23826',
       '23828', '23829'],
      dtype='object', name='name', length=2385)
Traceback (most recent call last):
  File "etrago/appl.py", line 515, in <module>
    etrago = run_etrago(args, json_path=None)
  File "etrago/appl.py", line 479, in run_etrago
    etrago.spatial_clustering()
  File "d:\etrago\etrago\cluster\networkclustering.py", line 1419, in run_spatial_clustering
    self.clustering, busmap = kmean_clustering(self)
  File "d:\etrago\etrago\cluster\networkclustering.py", line 960, in kmean_clustering
    tol=kmean_settings["tol"],
  File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\pypsa\networkclustering.py", line 475, in busmap_by_kmeans
    kmeans.fit(points)
  File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\sklearn\cluster\_kmeans.py", line 1180, in fit
    X, x_squared_norms=x_squared_norms, init=init, random_state=random_state
  File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\sklearn\cluster\_kmeans.py", line 1094, in _init_centroids
    x_squared_norms=x_squared_norms,
  File "C:\ProgramData\mambaforge\envs\test\lib\site-packages\sklearn\cluster\_kmeans.py", line 184, in _kmeans_plusplus
    centers = np.empty((n_clusters, n_features), dtype=X.dtype)
ValueError: negative dimensions are not allowed
```
