### ISSUE TITLE
lopf failing when using kmean_clustering_gas()

### ISSUE THREAD

**Issue by CarlosEpia** [openego/eTraGo#471]
I am getting the error that can be found below when using the spatial_clustering. It does not happen when I don't run etrago.spatial_clustering() part. @pieterhexen and @fwitte can you confirm if it is also happening to you? 
```
INFO:pypsa.opf:Solving model using gurobi
INFO:pypsa.opf:Optimization successful
# ==========================================================
# = Solver Results                                         =
# ==========================================================
# ----------------------------------------------------------
#   Problem Information
# ----------------------------------------------------------
Problem: 
- Name: x1236
  Lower bound: 275548875.4946279
  Upper bound: 275548875.4946279
  Number of objectives: 1
  Number of constraints: 1209
  Number of variables: 1236
  Number of binary variables: 0
  Number of integer variables: 0
  Number of continuous variables: 1236
  Number of nonzeros: 2846
  Sense: minimize
# ----------------------------------------------------------
#   Solver Information
# ----------------------------------------------------------
Solver: 
- Status: ok
  Return code: 0
  Message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
  Termination condition: optimal
  Termination message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
  Wall time: 0.004590034484863281
  Error rc: 0
  Time: 0.19167542457580566
# ----------------------------------------------------------
#   Solution Information
# ----------------------------------------------------------
Solution: 
- number of solutions: 0
  number of solutions displayed: 0
/home/student/venv/etrago_env6/lib/python3.7/site-packages/pypsa/opf.py:1298: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  .sum(level=1) \
Traceback (most recent call last):

  File "/home/student/venv/etrago_env6/lib/python3.7/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/home/student/git/eTraGo/etrago/appl.py", line 505, in <module>
    etrago = run_etrago(args, json_path=None)

  File "/home/student/git/eTraGo/etrago/appl.py", line 485, in run_etrago
    etrago.lopf()

  File "/home/student/git/eTraGo/etrago/tools/execute.py", line 251, in lopf
    method=self.args['method'])

  File "/home/student/git/eTraGo/etrago/tools/execute.py", line 178, in iterate_lopf
    run_lopf(etrago, extra_functionality, method)

  File "/home/student/git/eTraGo/etrago/tools/execute.py", line 121, in run_lopf
    formulation=etrago.args['model_formulation'])

  File "/home/student/venv/etrago_env6/lib/python3.7/site-packages/pypsa/components.py", line 658, in lopf
    return network_lopf(self, **args)

  File "/home/student/venv/etrago_env6/lib/python3.7/site-packages/pypsa/opf.py", line 1675, in network_lopf
    extra_postprocessing=extra_postprocessing)

  File "/home/student/venv/etrago_env6/lib/python3.7/site-packages/pypsa/opf.py", line 1585, in network_lopf_solve
    extra_postprocessing=extra_postprocessing)

  File "/home/student/venv/etrago_env6/lib/python3.7/site-packages/pypsa/opf.py", line 1316, in extract_optimisation_results
    set_from_series(network.links_t.p0, get_values(model.link_p))

AttributeError: 'dict' object has no attribute 'p0'
```

**Comment by pieterhexen** [comment]
@CarlosEpia I just tried to run the code but ran into licencing problem. I'll get back to you tomorror.

**Comment by fwitte** [comment]
Hmm, super weird. The overwriting of links and links_t with the `group_links` method in the gas kmeans clustering does something slightly different than in the networkclustering. The data in `links_t` is stored in a dict in contrary to the expected dataformat, which is a `pypsa.descriptors.Dict`. I'll make a PR to fix that.
