### ISSUE TITLE
Kmean clustering error by different num_parallel

### ISSUE THREAD

**Issue by wolfbunke** [openego/eTraGo#86]
The functionality  k_mean_clustering is not working if `num_parallel` isn't equal.

The function aggregatelines / aggregatelinegroup in pypsa/pypsa/networkclustering.py needs to be improved in order to handle this case. 

see bug report:
```
<class 'numpy.float64'>
12989    1.0
14046    2.0
2264     2.0
14045    2.0
18295    2.0
Name: num_parallel, dtype: float64
1.0
<class 'numpy.float64'>
2.0
<class 'numpy.float64'>
2.0
<class 'numpy.float64'>
2.0
<class 'numpy.float64'>
2.0
<class 'numpy.float64'>
Traceback (most recent call last):
  File "appl.py", line 309, in <module>
    network = etrago(args)
  File "appl.py", line 261, in etrago
    network = kmean_clustering(network, n_clusters=args['k_mean_clustering'])
  File "/home/dozeumbuw/eTraGo/src/eTraGo/etrago/cluster/networkclustering.py", line 341, in kmean_clustering
    clustering = get_clustering_from_busmap(network, busmap)
  File "/home/dozeumbuw/eTraGo/src/pypsa/pypsa/networkclustering.py", line 220, in get_clustering_from_busmap
    buses, linemap, linemap_p, linemap_n, lines = get_buses_linemap_and_lines(network, busmap, line_length_factor, bus_strategies)
  File "/home/dozeumbuw/eTraGo/src/pypsa/pypsa/networkclustering.py", line 204, in get_buses_linemap_and_lines
    lines, linemap_p, linemap_n, linemap = aggregatelines(network, buses, interlines, line_length_factor)
  File "/home/dozeumbuw/eTraGo/src/pypsa/pypsa/networkclustering.py", line 184, in aggregatelines
    lines = interlines_c.groupby(['bus0_s', 'bus1_s']).apply(aggregatelinegroup)
  File "/home/dozeumbuw/eTraGo/lib/python3.5/site-packages/pandas/core/groupby.py", line 694, in apply
    return self._python_apply_general(f)
  File "/home/dozeumbuw/eTraGo/lib/python3.5/site-packages/pandas/core/groupby.py", line 698, in _python_apply_general
    self.axis)
  File "/home/dozeumbuw/eTraGo/lib/python3.5/site-packages/pandas/core/groupby.py", line 1601, in apply
    res = f(group)
  File "/home/dozeumbuw/eTraGo/src/pypsa/pypsa/networkclustering.py", line 181, in aggregatelinegroup
    data.update((f, _consense(l[f])) for f in columns.difference(data))
  File "/home/dozeumbuw/eTraGo/src/pypsa/pypsa/networkclustering.py", line 181, in <genexpr>
    data.update((f, _consense(l[f])) for f in columns.difference(data))
  File "/home/dozeumbuw/eTraGo/src/pypsa/pypsa/networkclustering.py", line 54, in _consense
    assert ((x == v).all() or x.isnull().all())
AssertionError
```

**Comment by wolfbunke** [comment]
ok, in connection with line_grouping it doesn't work. I will write it to the doc string.
