### ISSUE TITLE
error by using glpk Solver

### ISSUE THREAD

**Issue by wolfbunke** [openego/eTraGo#87]
accidentally I used the standard glpk and following error appeared. By using gurobi everthing works fine.
```
INFO:pypsa.opf:Building pyomo model using `angles` formulation
INFO:pypsa.opf:Solving model using glpk
ERROR: Expecting 's' row after 'c' rows
Traceback (most recent call last):
  File "/home/dozeumbuw/eTraGo/lib/python3.5/site-packages/pyomo/solvers/plugins/solvers/GLPK.py", line 351, in process_soln_file
    raise ValueError("Expecting 's' row after 'c' rows")
ValueError: Expecting 's' row after 'c' rows

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "appl.py", line 310, in <module>
    network = etrago(args)
  File "appl.py", line 276, in etrago
    network.lopf(scenario.timeindex, solver_name=args['solver'], extra_functionality=extra_functionality)
  File "/home/dozeumbuw/eTraGo/src/pypsa/pypsa/opf.py", line 1099, in network_lopf
    keepfiles=keep_files, options=solver_options)
  File "/home/dozeumbuw/eTraGo/lib/python3.5/site-packages/pyomo/opt/base/solvers.py", line 610, in solve
    result = self._postsolve()
  File "/home/dozeumbuw/eTraGo/lib/python3.5/site-packages/pyomo/opt/solver/shellcmd.py", line 268, in _postsolve
    results = self.process_output(self._rc)
  File "/home/dozeumbuw/eTraGo/lib/python3.5/site-packages/pyomo/opt/solver/shellcmd.py", line 330, in process_output
    self.process_soln_file(results)
  File "/home/dozeumbuw/eTraGo/lib/python3.5/site-packages/pyomo/solvers/plugins/solvers/GLPK.py", line 362, in process_soln_file
    raise ValueError(msg)
ValueError: Error parsing solution data file, line 2
```

**Comment by BartelsJ** [comment]
Maybe you can try to install the pyomo master branch version. See closed issue [#59](https://github.com/openego/eTraGo/issues/59).

**Comment by wolfbunke** [comment]
ok, thank you!

**Comment by lukasoldi** [comment]
resolved? @wolfbunke

**Comment by wolfbunke** [comment]
yes
